### ISSUE TITLE
Já pensaram em construir um extension para o package?

### ISSUE THREAD

**Issue by rodrigorahman** [CriandoGames/all_validations_br#1]
Fala galerinha não é uma erro e sim uma sugestão ... já pensaram em criar uma extension para o package? 

Acredito que criar uma extension de num e String para as principais chamadas seria algo muito útil.

Se acharem que faz sentido me avise que eu mesmo posso contribuir para o package criando essa extension ;-)

Inclusive para ajudar vocês com a divulgação vou criar um vídeo no meu canal falando dele blz? ;-)

Grande abraço e parabéns pela iniciativa.

;-)

**Comment by CriandoGames** [comment]
A que honrar, obrigado  :) vamos conversar mais; podemos ajudar no desenvolvimento meu WhatsApp 
‪+1 (409) 995‑1874‬
