### ISSUE TITLE
isPhoneNumber está aceitando formato inválido

### ISSUE THREAD

**Issue by lucascriasol** [CriandoGames/all_validations_br#3]
Analisando o validador do GetUtils, achei essa diferença na expressão regular:

```
static bool isPhoneNumber(String s) {
    if (s.length > 16 || s.length < 9) return false;
    return hasMatch(s, r'^[+]*[(]{0,1}[0-9]{1,4}[)]{0,1}[-\s\./0-9]*$');
  }
```

Dessa forma, o seguinte teste passa a retornar corretamente o formato inválido:
```
expect(
        PhoneNumber.create('/31) 9#8888-7777').left,
        isA<ValueTypeDomainError>(),
      );
```

**Comment by CriandoGames** [comment]
Resolvido[ link do commit 

- [ V] ](https://github.com/CriandoGames/all_validations_br/commit/471dad78ff62d91a3d18f337e5457e0a398ec807)
